spring.application.name=BatteryMantra

#Spring Data JPA Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/batterymantra}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Ankur@123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:true}

#Spring Security Configuration
jwt.secretKey=${JWT_SECRET_KEY:ja827b3aaf88f2e53265a4ed9bd36556az26h2u8cfa169076d47782hgxz8}

#Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.cache.type=${SPRING_CACHE_TYPE:redis}
